services:
- type: web
  name: kmedya
  runtime: python
  repo: https://github.com/kmedya-dev/my-portfolio
  branch: full-stack
  plan: free
  region: singapore
  buildCommand: ./build.sh
  startCommand: gunicorn my_portfolio_backend.wsgi
  healthCheckPath: /healthz
  envVars:
    - key: DJANGO_SUPERUSER_USERNAME
      value: your_superuser_username
    - key: DJANGO_SUPERUSER_PASSWORD
      value: your_superuser_password
  autoDeployTrigger: commit
  rootDir: ./
  previews:
    generation: manual
version: "1"