# Generated by Django 5.2.4 on 2025-07-14 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='gist_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='gist_id',
            field=models.CharField(blank=True, help_text="Enter the ID of the GitHub Gist (e.g., 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
