name: Django Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v3

      - name:  Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name:  Install Dependencies & Run Build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          chmod +x build.sh
          ./build.sh